select * from __EFMigrationsHistory
select * from AspNetRoleClaims
select * from AspNetRoles
select * from AspNetUserLogins
select * from AspNetUserClaims
select * from AspNetUserRoles
select * from AspNetUsers
select * from AspNetUserTokens
select * from Batches
select * from Sections
select * from Students